[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
authors = [
    "Seth <seth@gmail.com>",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.0"

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"
